// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/pulse.proto

package pulsepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataPoint) Reset() {
	*x = DataPoint{}
	mi := &file_api_proto_pulse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPoint) ProtoMessage() {}

func (x *DataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pulse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPoint.ProtoReflect.Descriptor instead.
func (*DataPoint) Descriptor() ([]byte, []int) {
	return file_api_proto_pulse_proto_rawDescGZIP(), []int{0}
}

func (x *DataPoint) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DataPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Series struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Points        []*DataPoint           `protobuf:"bytes,3,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Series) Reset() {
	*x = Series{}
	mi := &file_api_proto_pulse_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Series) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Series) ProtoMessage() {}

func (x *Series) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pulse_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Series.ProtoReflect.Descriptor instead.
func (*Series) Descriptor() ([]byte, []int) {
	return file_api_proto_pulse_proto_rawDescGZIP(), []int{1}
}

func (x *Series) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *Series) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Series) GetPoints() []*DataPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type WriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Series        []*Series              `protobuf:"bytes,1,rep,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_api_proto_pulse_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pulse_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_pulse_proto_rawDescGZIP(), []int{2}
}

func (x *WriteRequest) GetSeries() []*Series {
	if x != nil {
		return x.Series
	}
	return nil
}

type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Written       int32                  `protobuf:"varint,1,opt,name=written,proto3" json:"written,omitempty"` // количество записанных серий
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_api_proto_pulse_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pulse_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_pulse_proto_rawDescGZIP(), []int{3}
}

func (x *WriteResponse) GetWritten() int32 {
	if x != nil {
		return x.Written
	}
	return 0
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	From          int64                  `protobuf:"varint,3,opt,name=from,proto3" json:"from,omitempty"` // Unix nanoseconds, 0 = без ограничения
	To            int64                  `protobuf:"varint,4,opt,name=to,proto3" json:"to,omitempty"`     // Unix nanoseconds, 0 = без ограничения
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_api_proto_pulse_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pulse_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_pulse_proto_rawDescGZIP(), []int{4}
}

func (x *QueryRequest) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *QueryRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *QueryRequest) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *QueryRequest) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Series        []*Series              `protobuf:"bytes,1,rep,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_api_proto_pulse_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pulse_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_pulse_proto_rawDescGZIP(), []int{5}
}

func (x *QueryResponse) GetSeries() []*Series {
	if x != nil {
		return x.Series
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	From          int64                  `protobuf:"varint,3,opt,name=from,proto3" json:"from,omitempty"`
	To            int64                  `protobuf:"varint,4,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_api_proto_pulse_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pulse_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_pulse_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRequest) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *DeleteRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *DeleteRequest) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *DeleteRequest) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_api_proto_pulse_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pulse_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_pulse_proto_rawDescGZIP(), []int{7}
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_api_proto_pulse_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pulse_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_pulse_proto_rawDescGZIP(), []int{8}
}

func (x *SubscribeRequest) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *SubscribeRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_api_proto_pulse_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pulse_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_pulse_proto_rawDescGZIP(), []int{9}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "ok"
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_proto_pulse_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pulse_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_pulse_proto_rawDescGZIP(), []int{10}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_api_proto_pulse_proto protoreflect.FileDescriptor

const file_api_proto_pulse_proto_rawDesc = "" +
	"\n" +
	"\x15api/proto/pulse.proto\x12\x05pulse\"?\n" +
	"\tDataPoint\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"\xb8\x01\n" +
	"\x06Series\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x121\n" +
	"\x06labels\x18\x02 \x03(\v2\x19.pulse.Series.LabelsEntryR\x06labels\x12(\n" +
	"\x06points\x18\x03 \x03(\v2\x10.pulse.DataPointR\x06points\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"5\n" +
	"\fWriteRequest\x12%\n" +
	"\x06series\x18\x01 \x03(\v2\r.pulse.SeriesR\x06series\")\n" +
	"\rWriteResponse\x12\x18\n" +
	"\awritten\x18\x01 \x01(\x05R\awritten\"\xbe\x01\n" +
	"\fQueryRequest\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x127\n" +
	"\x06labels\x18\x02 \x03(\v2\x1f.pulse.QueryRequest.LabelsEntryR\x06labels\x12\x12\n" +
	"\x04from\x18\x03 \x01(\x03R\x04from\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\x03R\x02to\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"6\n" +
	"\rQueryResponse\x12%\n" +
	"\x06series\x18\x01 \x03(\v2\r.pulse.SeriesR\x06series\"\xc0\x01\n" +
	"\rDeleteRequest\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x128\n" +
	"\x06labels\x18\x02 \x03(\v2 .pulse.DeleteRequest.LabelsEntryR\x06labels\x12\x12\n" +
	"\x04from\x18\x03 \x01(\x03R\x04from\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\x03R\x02to\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x10\n" +
	"\x0eDeleteResponse\"\xa2\x01\n" +
	"\x10SubscribeRequest\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x12;\n" +
	"\x06labels\x18\x02 \x03(\v2#.pulse.SubscribeRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x0f\n" +
	"\rHealthRequest\"B\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion2\x99\x02\n" +
	"\aPulseDB\x122\n" +
	"\x05Write\x12\x13.pulse.WriteRequest\x1a\x14.pulse.WriteResponse\x122\n" +
	"\x05Query\x12\x13.pulse.QueryRequest\x1a\x14.pulse.QueryResponse\x125\n" +
	"\x06Delete\x12\x14.pulse.DeleteRequest\x1a\x15.pulse.DeleteResponse\x128\n" +
	"\tSubscribe\x12\x17.pulse.SubscribeRequest\x1a\x10.pulse.DataPoint0\x01\x125\n" +
	"\x06Health\x12\x14.pulse.HealthRequest\x1a\x15.pulse.HealthResponseB1Z/github.com/bbvtaev/pulse-core/api/proto;pulsepbb\x06proto3"

var (
	file_api_proto_pulse_proto_rawDescOnce sync.Once
	file_api_proto_pulse_proto_rawDescData []byte
)

func file_api_proto_pulse_proto_rawDescGZIP() []byte {
	file_api_proto_pulse_proto_rawDescOnce.Do(func() {
		file_api_proto_pulse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_pulse_proto_rawDesc), len(file_api_proto_pulse_proto_rawDesc)))
	})
	return file_api_proto_pulse_proto_rawDescData
}

var file_api_proto_pulse_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_proto_pulse_proto_goTypes = []any{
	(*DataPoint)(nil),        // 0: pulse.DataPoint
	(*Series)(nil),           // 1: pulse.Series
	(*WriteRequest)(nil),     // 2: pulse.WriteRequest
	(*WriteResponse)(nil),    // 3: pulse.WriteResponse
	(*QueryRequest)(nil),     // 4: pulse.QueryRequest
	(*QueryResponse)(nil),    // 5: pulse.QueryResponse
	(*DeleteRequest)(nil),    // 6: pulse.DeleteRequest
	(*DeleteResponse)(nil),   // 7: pulse.DeleteResponse
	(*SubscribeRequest)(nil), // 8: pulse.SubscribeRequest
	(*HealthRequest)(nil),    // 9: pulse.HealthRequest
	(*HealthResponse)(nil),   // 10: pulse.HealthResponse
	nil,                      // 11: pulse.Series.LabelsEntry
	nil,                      // 12: pulse.QueryRequest.LabelsEntry
	nil,                      // 13: pulse.DeleteRequest.LabelsEntry
	nil,                      // 14: pulse.SubscribeRequest.LabelsEntry
}
var file_api_proto_pulse_proto_depIdxs = []int32{
	11, // 0: pulse.Series.labels:type_name -> pulse.Series.LabelsEntry
	0,  // 1: pulse.Series.points:type_name -> pulse.DataPoint
	1,  // 2: pulse.WriteRequest.series:type_name -> pulse.Series
	12, // 3: pulse.QueryRequest.labels:type_name -> pulse.QueryRequest.LabelsEntry
	1,  // 4: pulse.QueryResponse.series:type_name -> pulse.Series
	13, // 5: pulse.DeleteRequest.labels:type_name -> pulse.DeleteRequest.LabelsEntry
	14, // 6: pulse.SubscribeRequest.labels:type_name -> pulse.SubscribeRequest.LabelsEntry
	2,  // 7: pulse.PulseDB.Write:input_type -> pulse.WriteRequest
	4,  // 8: pulse.PulseDB.Query:input_type -> pulse.QueryRequest
	6,  // 9: pulse.PulseDB.Delete:input_type -> pulse.DeleteRequest
	8,  // 10: pulse.PulseDB.Subscribe:input_type -> pulse.SubscribeRequest
	9,  // 11: pulse.PulseDB.Health:input_type -> pulse.HealthRequest
	3,  // 12: pulse.PulseDB.Write:output_type -> pulse.WriteResponse
	5,  // 13: pulse.PulseDB.Query:output_type -> pulse.QueryResponse
	7,  // 14: pulse.PulseDB.Delete:output_type -> pulse.DeleteResponse
	0,  // 15: pulse.PulseDB.Subscribe:output_type -> pulse.DataPoint
	10, // 16: pulse.PulseDB.Health:output_type -> pulse.HealthResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_proto_pulse_proto_init() }
func file_api_proto_pulse_proto_init() {
	if File_api_proto_pulse_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_pulse_proto_rawDesc), len(file_api_proto_pulse_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_pulse_proto_goTypes,
		DependencyIndexes: file_api_proto_pulse_proto_depIdxs,
		MessageInfos:      file_api_proto_pulse_proto_msgTypes,
	}.Build()
	File_api_proto_pulse_proto = out.File
	file_api_proto_pulse_proto_goTypes = nil
	file_api_proto_pulse_proto_depIdxs = nil
}
